### ISSUE TITLE
Clarification for conformance of paragraph 7.4.2 with multiple tracks

### ISSUE THREAD

**Issue by rbouqueau** [MPEGGroup/MIAF#1]
MIAF paragraph 7.4.2:

> Thumbnail or auxiliary sequences shall conform either to the requirements of the same MIAF codec profile as the MIAF image sequence or video to which it is linked, or to the requirements of a format defined in clause 9

From our latest discussions a "MIAF codec profile" is equivalent to a MIAF Profile. MIAF profiles are indicated in the 'ftyp' box i.e. once per file. For a MIAF content with several tracks (each of them having a thumbnail or auxiliary sequence), how can we know which track refers to which MIAF Profile?

This is needed for the conformance software, see https://github.com/gpac/ComplianceWarden/issues/4

**Comment by dwsinger** [comment]
This is actually a problem at a deeper level — how do you determine which track corresponds to a profile claimed in the filetypebox? Say there are the brands of two profiles in the filetypebox, A and B, and you support A but not B. A and B use the same codec. In the file there are tracks marked as alternatives, two of which use this codec. One probably corresponds to A and the other to B. But which is which? 

If we can answer this question, we could also determine whether the thumbnail track conforms to the same profile.

**Comment by mhannuksela** [comment]
I suppose that the TrackTypeBox can be used. An excerpt from ISOBMFF:

> The payload of TrackTypeBox has the same syntax as the payload of FileTypeBox. The content of an instance of TrackTypeBox shall be such that it would apply as the content of FileTypeBox, if all other tracks of the file were removed and only the track containing this box, and the tracks it references by means of track references, remained in the file.

**Comment by cconcolato** [comment]
The group discussed the issue as part of the ballot of the CDAM2 and decided to add a recommendation to use the TrackTypeBox box (in tracks) or the BrandProperty box (in items) when all the tracks or items in the file don't share the same brand and when the brand/track or brand/item association cannot be easily determined (e.g. when the 4cc of the sample entry/item type is the same).

**Comment by cconcolato** [comment]
The group discussed it again and agreed to close the issue given the change in the amendment.

**Comment by rbouqueau** [comment]
@cconcolato Do we have samples for that or not yet?
