### ISSUE TITLE
Construction method support and the 'imda' box

### ISSUE THREAD

**Issue by cconcolato** [MPEGGroup/MIAF#10]
ISO/IEC 14496-12 6th edition AMD 2 introduced "Box relative data addressing" and changed `construction_method` 0 required in MIAF as follows:
> In 8.11.3.1, replace the following paragraph:
> i.	file_offset: by absolute byte offsets into the file at data_reference_index;  (construction_method == 0)  
> with:
> i.	file_offset: by absolute byte offsets into the file or the payload of IdentifiedMediaDataBox referenced by data_reference_index;  (construction_method == 0)

Given that it was introduced after MIAF was designed, it cannot be supported by old MIAF implementations. We should clarify MIAF to indicate that it is not supported, at least under the existing MIAF brand.

**Comment by krasimirkolarov** [comment]
Please check if this was addressed by Ed. 2 of MIAF

**Comment by cconcolato** [comment]
Indeed, the following note was added:
NOTE:	ISO/IEC 14496-12 also allows relative addressing of data across boxes in the same file by utilizing IdentifiedMediaDataBox (‘imda’). However, this is not supported under the ‘miaf’ brand.
