### ISSUE TITLE
Combined derivation chain and transformative properties

### ISSUE THREAD

**Issue by cconcolato** [MPEGGroup/MIAF#4]
MIAF indicates in 7.3.6.7 the following about  transformative properties:
> These properties, if used, shall be indicated to be applied in the following order: clean aperture first, then
rotation, then mirror.

MIAF also says the following in 7.3.11.1 about derivation chain:
> The maximum derivation chain is shown in the following list; the Identity, Grid and Overlay derivations are
optional. All derivation chains shall originate from one or more coded images. An identity derivation shall
not be derived immediately from another identity derivation. If derivations occur, they shall be in this
order:
— mandatory coded image(s)
— optional identity derivation (subclause 7.3.11.2)
— optional grid (subclause 7.3.11.4)
— optional identity derivation (subclause 7.3.11.2)
— optional overlay (subclause 7.3.11.3)
— optional identity derivation (subclause 7.3.11.2)

The current implementation of the validation tool (https://github.com/gpac/ComplianceWarden-wasm) assumes that the number and order of transformation applies to the list, i.e. that you cannot have a rotation on a coded image then a clap on a grid for example. 

In the context of AVIF, it has been indicated that allowing transformations at each level of the derivation chain is complex to implement and it is considered to restrict the transformations to the last step of the derivation chain. https://github.com/AOMediaCodec/av1-avif/issues/124

It would be interesting in general for MIAF to know the implementation status and usage status of combined derivation chains and transformative properties. Maybe we can restrict it ...

**Comment by leo-barnes** [comment]
I think our implementation supports basically the full chain described in MIAF, including transformative properties in the chain. But I don't think we ever _use_ transform properties on derived item inputs.

**Comment by cconcolato** [comment]
Overtaken by events.
