### ISSUE TITLE
Typo in MIAF ISO/IEC 23000-22:2019 DAmd 2

### ISSUE THREAD

**Issue by wantehchang** [MPEGGroup/MIAF#6]
I spotted what looks like a typo in MIAF ISO/IEC 23000-22:2019 DAmd 2.

The file has Reference number ISO/IEC 23000-22:2019/DAM 2:2021(E). Near the bottom of page 5, it says:

> _In subclause 7.3.5.2 “Alpha auxiliary image items” add after the bulleted list_
> 
> Given the semantics above, if a CICP colour property is associated with an alpha auxiliary image item,
> `full_range_flag` shall be set to 0.

I think it should say `full_range_flag` shall be set to **1**, not 0.

Wan-Teh Chang <wtc@google.com>

**Comment by cconcolato** [comment]
Thanks for the report. This has been fixed in the FDAM2.
