### ISSUE TITLE
Unneeded change in MIAF ISO/IEC 23000-22:2019 DAmd 2

### ISSUE THREAD

**Issue by wantehchang** [MPEGGroup/MIAF#7]
I would like to report an unneeded change in MIAF ISO/IEC 23000-22:2019 DAmd 2.

The file has Reference number ISO/IEC 23000-22:2019/DAM 2:2021(E). In the middle of page 6, it says:

> _Change the title of subclause 7.3.6.6 “Pixel Information” to “Pixel information”_

This change is not needed, because the title of subclause 7.3.6.6 in ISO/IEC 23000-22:2019(E) (on page 15) is already "Pixel information".

Wan-Teh Chang <wtc@google.com>

**Comment by cconcolato** [comment]
Thanks for the report. This change was removed from FDAM2.
